### ISSUE TITLE
fAsicEnabled vector not initialised

### ISSUE THREAD

**Issue by patrick-macgregor** [ISOLDESolenoidalSpectrometer/ISSSort#1]
In the Calibration.cc file, in the member function `Calibration::ReadCalibration()`, a number of vectors are initialised, but the `fAsicEnabled` vector is not initialised (around lines 22--27). The code compiles, but you end up with a segmentation fault. I was able to fix it by adding the line: `fAsicEnabled.resize( set->GetNumberOfArrayModules() );` to the Calibration.cc file.

**Comment by lpgaff** [comment]
Fixed in bca19833e83e3b31a2a15472dc787efd709060f4
