### ISSUE TITLE
Possible typo in Histogrammer?

### ISSUE THREAD

**Issue by ACeulemans** [ISOLDESolenoidalSpectrometer/ISSSort#10]
@dj-clarke : After the last update, I get the following error when using make. Could it be that it should be zbins.size() instead of zbin.size() for the number of bins?
![Histogrammer_zbins](https://user-images.githubusercontent.com/69502397/219616195-d69df37c-c57e-49e8-b6cc-23cd0f19021b.png)

**Comment by dj-clarke** [comment]
Yes, it should be zbins. I have sent a request to Liam to change it. Apologies for the typo.

**Comment by lpgaff** [comment]
Hi both, this was fixed in dd28fbb but it looks like I didn't push the changes to the main branch. Sorry about that.
