### ISSUE TITLE
Cuts in Ex and theta_cm

### ISSUE THREAD

**Issue by ACeulemans** [ISOLDESolenoidalSpectrometer/ISSSort#12]
After updating my version of the ISSsort code I am experiencing strange Ex and theta_cm histograms. Doesn't matter if I enable the butler algorithm or not. (currently on [d80bf0a](https://github.com/ISOLDESolenoidalSpectrometer/ISSSort/commit/d80bf0adeb91b60109e77cb8d075a6d1f4705d0c))
![image](https://user-images.githubusercontent.com/69502397/221822957-deea68ed-584b-4ee2-a885-654339705a80.png)
(this one without butler)

Also it looks like theta_cm is wrong (too low values)
@lpgaff Any idea what might have caused this?

**Comment by lpgaff** [comment]
Almost certainly my attemp to put the preprocessor flags in to the code. I will have a look at this this afternoon. Sorry.

Can you confirm that if you roll back to beaceea that it works?

**Comment by ACeulemans** [comment]
Yes, works on https://github.com/ISOLDESolenoidalSpectrometer/ISSSort/commit/beaceea1436a53973e357188d829d36bb92b6430 
Analysed just a few run files to check:
![image](https://user-images.githubusercontent.com/69502397/221864092-f3967351-a968-43c0-97ec-dc3579d49fb7.png)

**Comment by lpgaff** [comment]
I'm going to close this, as I think it is fixed in the latest versions, at least from commit d07cf4c74ffc17ef4d40a6eaed727da271cc4d85

**Comment by lpgaff** [comment]
I'm going to close this, as I think it is fixed in the latest versions, at least from commit d07cf4c74ffc17ef4d40a6eaed727da271cc4d85
