### ISSUE TITLE
array events missing

### ISSUE THREAD

**Issue by ACeulemans** [ISOLDESolenoidalSpectrometer/ISSSort#15]
@lpgaff : In the latest commit e007be20b4ee45e718ca461819784abbf57e59bb there seems to be something wrong with recognizing the array events. I have attached my log files for a single data file showing the difference between the current commit and earlier d80bf0a results.  Array p/n-side correlated events and  Array p-side only events changed drastically . The absence of correlated events also means the E vs z histogram only contains 6 instead of 209 entries, which indicates some are missing.

[log_r113_0.txt](https://github.com/ISOLDESolenoidalSpectrometer/ISSSort/files/11088095/log_r113_0.txt)

**Comment by lpgaff** [comment]
Apologies. I forgot to comment out a couple of lines after testing (unsuccessfully) the time walk event re-ordering. I think it is back to normal again now in commit [a237b5a](https://github.com/ISOLDESolenoidalSpectrometer/ISSSort/commit/a237b5a069abe0b99a40d14229a84c1eca0d1b9d).
