### ISSUE TITLE
Excitation energy spectrum

### ISSUE THREAD

**Issue by ACeulemans** [ISOLDESolenoidalSpectrometer/ISSSort#16]
Using commit bbcb371 I get a wrong excitation energy spectrum. Maybe it has something to do with the energy loss correction?
(see attachment)
![image](https://user-images.githubusercontent.com/69502397/229724840-10036516-c456-433f-b591-59522d8b446e.png)

For a237b5a the spectrum looked normal, but maybe the peaks where a bit wider than expected.

**Comment by lpgaff** [comment]
Line number 1160 in Reaction.cc should be alpha *= z;Argh. Sorry about these annoying typos. I don’t know how that version was the one that made it to GitHub. It’s correct on my laptop, but I must have not done the commits properly when switching to my new laptop last week. I’ll try to resync everything. In the meantime, try applying the update by hand?On 4 Apr 2023, at 08:51, ACeulemans ***@***.***> wrote:﻿
Using commit bbcb371 I get a wrong excitation energy spectrum. Maybe it has something to do with the energy loss correction?
(see attachment)

For a237b5a the spectrum looked normal, but maybe the peaks where a bit wider than expected.

**Comment by lpgaff** [comment]
Does [0d355b3](https://github.com/ISOLDESolenoidalSpectrometer/ISSSort/commit/0d355b3ab4238581775c04fd4d1e29e44a9f78af) fix it, @ACeulemans?

I guess you are using the "Butler algorithm"?

**Comment by ACeulemans** [comment]
I implemented your suggested fix, seems to work, I will check when I get the complete results tomorrow (code is running atm).
Yes, I am using the Butler algorithm.

**Comment by lpgaff** [comment]
Just FYI, changes to the Reaction code do not require any additional flags for the data sorting. Only the histogrammer stage needs to be re-run. That should be fast (of the order of minutes).

**Comment by ACeulemans** [comment]
I didn't realize that, should save me quite some time, thanks for letting me know.

**Comment by lpgaff** [comment]
Yes that is the design philosophy of the code. The difficult and slow things are done first, such as unpacking and time ordering, then the results are written to the root file. After that, the physics events are built and written to the events.root file (calibration is applied here if you need to update it). Finally, you make all of your coincidences, cuts, kinematics, etc, etc in the final histogramming steps, which takes of the order of minutes and produces a single output file with your combined statistics of all the individual input runs you give. 

If you already have a good set of _events.root files, you simple need to run ISSSort again when you change anything to do with the reaction file. This is true for target thickness, array distance, B field, beam energy, kinematics calculations, recoil cuts, EBIS cuts, E vs z cuts, and whatever else we can think off. 

Unless you change the energy calibration or time shifts/walks, you do not need to call again the event builder or time sorter.
