### ISSUE TITLE
Errant gamma3

### ISSUE THREAD

**Issue by patrick-macgregor** [ISOLDESolenoidalSpectrometer/ISSSort#17]
In the Reaction.cc file, in `theta_cm_function`, the calculation of `r_max` and `z` contain gamma3 parameters where they should not. By my reckoning:

$r_{max} = 2r = \dfrac{2\gamma_3m_3u_\perp}{qB} = \dfrac{2\gamma_3m_3\dfrac{p_3\sinθ_{lab}}{\gamma_3m_3}}{qB} = \dfrac{2p_3\sinθ_{lab}}{qB}$

and

$z = u_\parallel\cdot t_{cyc} = u_3\cosθ_{lab}\cdot 2π\dfrac{\gamma_3m_3}{qB} = \dfrac{p_3}{\gamma_3m_3}\cosθ_{lab}\cdot 2π\dfrac{\gamma_3m_3}{qB} = \dfrac{2\pi p_3\cosθ_{lab}}{qB}$

The current definitions in the Reaction.cc file are 
`144    double r_max = TMath::Abs( 2.0 * p3_lab * TMath::Sin( theta_lab ) / ( gamma3 * qb * TMath::TwoPi()) );`, so the `gamma3` should be deleted.

Also, `145    double z = p3_lab * TMath::Cos( theta_lab ) / ( gamma3 * qb );`, so the `gamma3` should be removed here as well. As far as I can tell, the $2\pi$ is contained in the line `101    double qb = params[3]; //  over 2*pi`. Hope that makes sense and that it can be amended anywhere else...

**Comment by lpgaff** [comment]
Can you please check that commits fee3124f2b0a27696da815ddb3b2ebafede0219c (v2.1) and 55f6a5a81257bc9d2cb5e54ecf09e05e46f5d2a3 (master) solve this? They are both the same commit, but on the two versions of the code before and after the updates to the event tree format.
