### ISSUE TITLE
Segmentation violation when running event building

### ISSUE THREAD

**Issue by ACeulemans** [ISOLDESolenoidalSpectrometer/ISSSort#26]
@lpgaff: I get a segmentation violation when using the latest commit with the real data (nptool data works fine), during the event building step.
This happens with the latest commit [8c39cbb](https://github.com/ISOLDESolenoidalSpectrometer/ISSSort/commit/8c39cbb9c589de7899634898ed8a504da84b2570)
, the same command still worked fine with commit 8e3b9a2.

Seems to be an issue with deleting a smart pointer ISSAsicData* (defined in EventBuilder.hh)
It is complaining about EventBuilder.cc line 440:
input_tree->BuildIndex( "GetTimeStamp()" );

Abbreviated/filtered stack trace (I can send the full one if you want it):

 5  in std::_Destroy < ISSAsicData >
 6   in std::_Destroy_aux<false>::__destroy<ISSAsicData*>
 21  in ISSEventBuilder::BuildEvents at src/EventBuilder.cc:440
22  in do_build () at iss_sort.cc:406

**Comment by lpgaff** [comment]
Thanks for reporting, I can reproduce this. I will try to fix it and update you soon...

**Comment by ACeulemans** [comment]
Doesn't seem to be solved in 0311b2f , but I don't see any changes to Eventbuilder in the latest two commits, so maybe I am overlooking something. 
The issue for reproduction might be that it doesn't occur for every file, only the second file in my input gives the error.

**Comment by ACeulemans** [comment]
The new commit does not seem to make a difference. To be honest I am not really an expert on pointer or how they interact with root. Is there anything I can do to help with this issue?

**Comment by lpgaff** [comment]
That's weird, because I have now removed all the smart pointer things... Maybe it is something else. I'll have to re-trace the steps with the various commits to see when the issue started. You could maybe help with that? Isolate exactly which commit broke things?

**Comment by lpgaff** [comment]
OH WAIT! I think I've found it... Sorry, I am stupid.

`	inline void CloseOutput(){
		output_tree->ResetBranchAddresses();
		PurgeOutput();
		output_file->Close();
		//input_tree->ResetBranchAddresses();
		//nptool_tree->ResetBranchAddresses();
		input_file->Close();
		if( in_data != nullptr ) delete in_data;
		if( sim_data != nullptr ) delete sim_data;
		log_file.close(); //?? to close or not to close?
	}; ///< Closes the output files from this class
`

Looks like I added a delete call for `in_data` in the CloseOutput() function, which is called at the end of a file. That means, if you have two files, the second file will start with the `in_data` pointer having been deleted!

I've just made a new pull request #29 to revert some of the previous changes and make a proper fix by commenting out those delete lines...

Can you try again? Sorry for the annoying bug! Totally my fault...

**Comment by ACeulemans** [comment]
Yes now the event building does work past the 2nd file. The problem seems to be solved.

**Comment by lpgaff** [comment]
Thanks for confirming... Sorry about that.
