### ISSUE TITLE
Bug filling OffBeam Ex_ebis_on_mod in Histogrammer.cc

### ISSUE THREAD

**Issue by dj-clarke** [ISOLDESolenoidalSpectrometer/ISSSort#6]
OffBeam events are not subtracted from the Ex_vs_z_ebis_mod histogram.

The histogram should be filled as

Ex_vs_z_ebis_mod[array_evt->GetModule()]->Fill( react->GetZmeasured(), react->GetEx(), -1.0 * react->GetEBISFillRatio() );

for OffBeam events.

**Comment by lpgaff** [comment]
Thanks for spotting this and reporting it. I've now fixed it in bbe954c170005ee21de9e3f992c3a516c39d0065.
